
service: serverless-image-labelling

plugins:
  - serverless-python-requirements

package:
  individually: true
  include:
    - '!*'
    - '!**'
    - handlers/*.py

provider:
  name: aws
  logs:
    restApi:
      role: arn:aws:iam::774013796425:role/ServerlessAPIGatewayLogsRole
      roleManagedExternally: true # disables automatic role creation/checks done by Serverless
      # + create role manually: https://coady.tech/aws-cloudwatch-logs-arn/
  runtime: python3.11
  stage: dev
  region: us-east-1
  environment:
    LABEL_TO_S3_MAPPING_TABLE: 'label-to-s3-mapping-table'
    MASTER_IMAGE_TABLE: 'master-image-label-table'
    SERVERLESS_IMAGE_LABELLING_BUCKET: 'serverless-image-labelling-bucket-arye'
    REGION_NAME: 'us-east-1'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:provider.environment.SERVERLESS_IMAGE_LABELLING_BUCKET}/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.LABEL_TO_S3_MAPPING_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MASTER_IMAGE_TABLE}"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"

functions:
  labelOnS3Upload:
    handler: handlers/S3UploadHandler.labelOnS3Upload
    events:
      - s3:
          bucket: ${self:provider.environment.SERVERLESS_IMAGE_LABELLING_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
  getImagesByLabel:
    handler: handlers/getImagesByLabelHandler.getImagesByLabel
    events:
      - http:
          path: getImagesByLabel
          method: post
          cors: true
